zhihu/urls.py
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.conf import settings
from django.contrib import admin


urlpatterns = [
    url(r'^', include('site_page.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('site_page.api.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

site_page/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save
from django.dispatch import receiver


class UserProfile(models.Model):
    belong_to = models.OneToOneField(to=User, related_name='profile')
    name = models.CharField(max_length=128, null=True, blank=True)
    email = models.EmailField(null=True)
    phone = models.CharField(max_length=11, null=True, blank=True)
    desc = models.CharField(null=True, blank=True, max_length=250)
    avatar = models.ImageField(upload_to='avatars', default='/avatars/default.png')
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Topic(models.Model):
    name = models.CharField(null=True, blank=True, max_length=14)
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name


class Question(models.Model):
    author = models.ForeignKey(to=UserProfile, related_name='question_author')
    title = models.CharField(null=True, blank=True, max_length=100)
    desc = models.TextField(null=True, blank=True, max_length=1000)
    topics = models.ForeignKey(to=Topic, related_name='question', null=True)
    answer_counts = models.IntegerField(default=0)
    create_time = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.title


class Answer(models.Model):
    question = models.ForeignKey(to=Question, related_name='question_answer')
    author = models.ForeignKey(to=UserProfile, related_name='answer_author')
    user_vote = models.ManyToManyField(to=UserProfile, related_name='user_vote_answer', blank=True)
    content = models.TextField(null=True, blank=True)
    abstract = models.TextField(null=True, blank=True)
    like_counts = models.IntegerField(default=0)
    dislike_counts = models.IntegerField(default=0)
    comment_counts = models.IntegerField(default=0)
    create_time = models.DateTimeField(default=timezone.now, null=True)

    def __str__(self):
        return self.author.name


# 取答案前200字符做摘要
@receiver(post_save, sender=Answer)
def create_answer_abstract(sender, instance, created, **kwargs):
    if created:
        content = instance.content
        instance.abstract = content[:200]
        instance.save()


class Comment(models.Model):
    comment_user = models.ForeignKey(to=UserProfile, related_name='comment_author')
    user_ip = models.CharField(null=True, blank=True, max_length=30)
    belong_to = models.ForeignKey(to=Answer, related_name='answer_comments')
    # 父评论
    parent = models.ForeignKey(to='self', related_name='child_comments', null=True, blank=True)
    # 回复对象
    reply_to = models.ForeignKey(to='self', related_name='who_reply', null=True, blank=True)
    content = models.TextField(null=True, blank=True)
    create_time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.comment_user.name


class Vote(models.Model):
    owner = models.ForeignKey(to=UserProfile, related_name='user_vote')
    give_to = models.ForeignKey(to=Answer, related_name='vote')
    # 1是未作选择，2是赞同，3是反对
    vote = models.IntegerField(default=1)
    create_time = models.DateTimeField(default=timezone.now)

templates/css_js.html
{% load static %}

    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title">
    <link rel="stylesheet" href="{% static 'css/common.css' %}" media="screen" title="no title">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}" media="screen" title="no title">
    <script src="{% static 'js/vue1.js' %}"></script>
    <script src="{% static 'js/js.cookie.js' %}"></script>
    <script src="{% static 'js/reqwest.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/semantic.js' %}"></script>
    <script src="{% static 'login_register/md5.js' %}"></script>

templates/edit_profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑个人资料</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" media="screen" title="no title">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" media="screen" title="no title">
    {% include 'css_js.html' %}
</head>
<body id="app">
<div id="home-page" style="display: none">
{% include 'top_nav.html' %}
    <div class="edit-success-message" style="display: none">
      <p class="success-message">保存成功</p>
    </div>
    <div class="edit-err-message" style="display: none">
      <p class="err-message">[[err_msg]]</p>
    </div>
    <div class="ui basic container segment" style="width: 500px;">
        <table>
            <tbody>
                <tr>
                    <td><img :src="user_info.profile.avatar" style="width:100px;height:100px" /></td>
                    <td>
                        <form method="post" enctype="multipart/form-data" action="/profile/[[user_info.id]]/edit/">

                            <input id="id_avatar" name="avatar" type="file">
                            {% csrf_token %}
                            <button class="ui basic button" type="submit">修改头像</button>
                        </form>
                    </td>
                </tr>
                <tr>
                    <td>名字</td>
                    <td><div class="ui input"><input v-model="user_name" type="text" value="[[user_name]]"></div></td>
                </tr>
                <tr>
                    <td>一句话介绍</td>
                    <td><div class="ui input"><input v-model="user_desc" type="text" value="[[user_desc]]"></div></td>
                </tr>
            </tbody>
        </table>
        <button v-on:click="editProfile" style="margin-top: 25px" class="ui inverted blue button">保存</button>

    </div>
{% include 'footer.html' %}
</div>
    <script>
        Vue.config.delimiters = ["[[", "]]"];
        vm = new Vue({
            el: '#app',
            data:{
                err_msg:'',
                user_name: '',
                user_desc: '',
                user_info:'',
                login_or:false,
                question:{
                    title:'',
                    desc: '',
                    topic:''
                }
            },
            methods:{
                editProfile:function () {
                    var self = this;
                    reqwest({
                        url: '/api/edit_profile/' + self.user_info.id + '/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        method: 'post',
                        data:{
                            name: self.user_name,
                            desc: self.user_desc
                        },
                        success:function (resp) {
                            document.querySelector('.edit-success-message').style.cssText = "display:";
                            document.querySelector('.edit-err-message').style.cssText = "display:none";
                        },
                        error:function (err) {
                            message = err.response;
                            json_msg = JSON.parse(message);
                            self.err_msg = json_msg.msg;
                            document.querySelector('.edit-success-message').style.cssText = "display:none";
                            document.querySelector('.edit-err-message').style.cssText = "display:";
                        }
                    })
                },
                addQuestion:function () {
                    var self = this;
                        reqwest({
                        url: '/api/questions/',
                        type: 'json',
                        method: 'post',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        data:{
                            title:self.question.title,
                            desc: self.question.desc,
                            topic:self.question.topic
                        },
                        success:function (resp) {
                            window.location.href= '/question/'+resp.id+'/'
                        }
                    })
                },
                logOut:function () {
                    Cookies.remove('token');
                    location.reload()
                },
                request_user:function () {
                    var self = this;
                    reqwest({
                        url: '/api/users/now/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.user_info = resp;
                            self.login_or = true
                            },
                        error:function (err) {
                            json_msg = JSON.parse(err.response);
                            self.login_or = false
                        }
                    })
                },
                displayBody:function () {
                    document.querySelector('#home-page').style.cssText = "display:";
                }
            },
             ready:function () {
                this.request_user();
                this.displayBody();
            }
        })
    </script>
</body>
</html>

templates/footer.html
{% load static %}
{#<div class="ui basic segment footer" style="margin-top: 100px">#}
{#    <div class="ui divider" style="width:960px;height:3px;"></div>#}
{#    <div class="ui three column grid">#}
{#        <div class="column">#}
{#            <div class="footer1">Developed by Kirito</div>#}
{#        </div>#}
{#        <div class="column">#}
{#            <div class="footer2">关于我们 . 加入我们 . 联系我们</div>#}
{#        </div>#}
{#        <div class="column">#}
{#            <div class="footer3">京ICP备15047012号-2</div>#}
{#        </div>#}
{#    </div>#}
{#</div>#}

<div id="question-modal" class="ui segments modal">
    <div class="ui borderless menu modal-menu">
        <div class="item">
            <h3 class="ui inverted header">提问</h3>
        </div>
        <div class="right menu">
            <div class="item">
                <a href="javascript:$('.ui.modal').modal('hide')"><div class="ui circular image"><img src="{% static 'images/close_icon.png' %}" ></div></a>
            </div>
        </div>
    </div>
    <div class="ui basic segment container" style="left: 0">
        <div class="ui form">
            <div class="field">
                <input v-model="question.title" type="text" name="question" placeholder="写下你的问题">
            </div>
            <div class="field">
                <label style="margin: 15px 0 10px 0">问题说明：
                    <span style="float: right;"><img src="{% static 'images/img_icon.png' %}"></span>
                    <span class="" style="float: right; margin-right: 10px"><img src="{% static 'images/code_icon.png' %}"></span>
                </label>
                <textarea v-model="question.desc" placeholder="问题背景、相关代码及截图等详细信息"></textarea>
            </div>
            <div class="field">
                <label style="margin: 15px 0 10px 0">添加话题：</label>
                <input v-model="question.topic" type="text" name="" placeholder="话题之间用空格隔开">
            </div>
        </div>
        <button v-on:click="addQuestion" class="ui blue right floated button" style="margin-top: 25px">发布</button>
        <a href="javascript:$('.ui.modal').modal('hide')" class="ui inverted right floated button" style="margin-top: 25px; color: #6699CC">取消</a>
    </div>
</div>


<div id="register-modal" class="ui basic modal">
    <div class="ui segment container" style="width: 302px;height: 331px;border-radius: 5px;
    box-shadow: 0 0 15px 0 rgba(0,0,0,.3);">
        <div style="color: black;text-align: right;margin-top: -6px;width: 280px">
            <i class="remove icon" onclick="javascript:$('.ui.modal').modal('hide')" style="cursor: pointer;"></i>
        </div>
        <div class="login-title" style="font-size: 16px;line-height: 18px;font-weight: 700;margin-top: 10px;color: #787878;text-align: center;">
            注册Exchange
            <div class="sub-title" style="font-size: 14px;font-weight: 400;text-align: center;margin-top: 9px">
                与世界分享你的知识、经验和见解
            </div>
        </div>
        <form class="ui form" id="login-form" style="margin-top: 15px;height: 205px">
            <div class="field" v-on:click="msgShow=false">
                <p id="form-message" v-if="msgShow">[[username_err]]</p>
                <input required v-model="username" type="text" name="username" placeholder="名字">
            </div>
            <div class="field" v-on:click="msgShow=false">
                <p id="form-message2" v-if="msgShow">[[email_err]]</p>
                <input v-model="email" type="email" name="email" placeholder="邮箱">
            </div>
            <div class="field" v-on:click="msgShow=false">
                <p id="form-message3" v-if="msgShow">[[password_err]]</p>
                <input v-model="password" type="password" name="password" placeholder="密码（六位以上）">
            </div>
            <a  class="ui blue button" style="width: 270px">注册</a>
        </form>
        <div class="login-foot" style="color: black;float: right;">
            已有帐号？<span><a style="cursor: pointer" onclick="$('#register-modal').modal('hide');$('#login-modal').modal('show')">登录</a></span>
        </div>
    </div>
</div>


<div id="login-modal" class="ui basic modal">
    <div class="ui segment container" style="width: 302px;height: 291px;border-radius: 5px;
    box-shadow: 0 0 15px 0 rgba(0,0,0,.3);">
		<div style="color: black;text-align: right;margin-top: -6px;width: 280px">
			<i class="remove icon" onclick="javascript:$('.ui.modal').modal('hide')" style="cursor: pointer;"></i>
		</div>
		<div class="login-title" style="font-size: 16px;line-height: 18px;font-weight: 700;margin-top: 10px;color: #787878;text-align: center;">
			登录Exchange
			<div class="sub-title" style="font-size: 14px;font-weight: 400;text-align: center;margin-top: 9px">
				与世界分享你的知识、经验和见解
			</div>
		</div>
		<form class="ui form" id="login-form" style="margin-top: 20px">
	        <div class="field" v-on:click="msgShow=false">
	            <p v-if="msgShow" id="form-message">[[email_err]]</p>
	            <input v-model="username" type="email" placeholder="邮箱">
	        </div>
	        <div class="field">
	            <p v-if="msgShow" id="form-message2">[[password_err]]</p>
	            <input v-model="password" type="password" placeholder="密码">
	        </div>
	        <a @click="logIn" class="ui blue button" style="width: 270px">登录</a>
	        <div class="login-foot" style="color: black;float: right;margin-top: 15px;">
	            忘记密码？
	        </div>
	    </form>
	</div>
</div>

templates/login_register.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Home</title>
  </head>
  <body>
    <div id="app">
    	<router-view ></router-view>

    </div>
    <script src="{% static 'login_register/build.js' %}"></script>
  <script src="{% static 'login_register/js.cookie.js' %}"></script>
  <script src="{% static 'login_register/md5.js' %}"></script>
  </body>
</html>

templates/peo_ask.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>个人中心页</title>
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" media="screen" title="no title">
    <link rel="stylesheet" href="{% static 'css/home.css' %}" media="screen" title="no title">
    {% include 'css_js.html' %}
</head>
<body id="app">
<div id="home-page" style="display: none">
{% include 'top_nav.html' %}

    <div class="ui basic container segment" style="height: 130px;">
        <div class="ui image">
            <img :src="visit_user.profile.avatar" style="width:100px;height:100px" />
        </div>
        <h3 id="user-name">
            [[visit_user.profile.name]]
            <span id="user-desc">[[visit_user.profile.desc ]]</span>
        </h3>
        <a id="editButton" href="/profile/[[visit_user.id]]/edit/" class="ui blue basic button" style="float: right;display: none">修改资料</a>
    </div>
    <div class="ui basic segment container">
        <div class="ui secondary pointing menu">
            <a id="user_like" class="item " href="/profile/[[visit_user.id]]/">
                赞过
            </a>
            <a id="user_ask" class="item active" href="/profile/[[visit_user.id]]/ask/">
                提问
            </a>
            <a id="user_answer" class="item" href="/profile/[[visit_user.id]]/answer/">
                回答
            </a>
        </div>

        <div class="ui segment">
                        
            <div v-if="user_question_show" id="question" class="ui items">
                <div class="item" v-for="question in user_asks">
                    <div class="content" style="padding-left:10px;">
                        <div>
                            <img class="right floated mini ui image" style="height: 30px;width: 30px" :src="question.author.avatar">
                            <div class="meta">
                                <a href="/profile/[[question.author.id]]/" style="font-weight:bold;color:#000000;">[[ question.author.name ]],</a>
                                <span style="color:#BFBFBF;font-size: 13px">[[ question.author.desc ]]</span>
                            </div>
                        </div>
                        <a href="/question/[[question.id]]/" class="header" style="color:#2e5e9f;font-size:14px;margin-top: 8px">
                            [[ question.title ]]
                        </a>
                        <p style="font-size: 13px;margin-top: 5px">
                            [[ question.desc ]]
                        </p>
                    </div>
                </div>
                <div class="ui divider"></div>
            </div>
            <div class="ui long button" v-show="noQuestion">
                <div class="header item">
                    <a>还没有提问...</a>
                </div>
            </div>
        </div>

    </div>
    {% include 'footer.html' %}
</div>
    <script>
        Vue.config.delimiters = ["[[", "]]"];
        vm = new Vue({
            el: '#app',
            data:{
                user_info:'',
                visit_user:'',
                login_or:false,
                question:{
                    title:'',
                    desc: '',
                    topic:''
                },
                like_answers:[],
                user_asks:[],
                user_answer_show:true,
                user_question_show:false,
                ask_active:'',
                answer_active:'',
                comments:[],
                noQuestion:false
            },
            methods:{
                addQuestionBtn:function () {
                    var self=this;
                    if (self.user_info==''){
                        return $('#register-modal').modal('show')
                    }else{
                        return $('#question-modal').modal('show');
                    }
                },
                ifLogin:function () {
                    var self=this;
                    if (self.user_info==''){
                        return $('#register-modal').modal('show')
                    }
                },
                addQuestion:function () {
                    var self = this;
                        reqwest({
                        url: '/api/questions/',
                        type: 'json',
                        method: 'post',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        data:{
                            title:self.question.title,
                            desc: self.question.desc,
                            topic:self.question.topic
                        },
                        success:function (resp) {
                            window.location.href= '/question/'+resp.id+'/'
                        }
                    })
                },
                getUser:function () {
                    var self = this;
                    reqwest({
                        url:'/api/user/' + {{ user_id }} +'/',
                        type: 'json',
                        success:function (resp) {
                            self.visit_user = resp;
                            self.userAsk()
                        }
                    })
                },
                userAsk:function () {
                    var self = this;
                    reqwest({
                        url: '/api/only_questions?user_id=' + self.visit_user.id,
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.user_asks = resp;
                            if (resp.length == 0){
                                self.noQuestion = true
                            }
                            console.log(resp)
                        }
                    })
                },
                logOut:function () {
                    Cookies.remove('token');
                    location.reload()
                },
                request_user:function () {
                    var self = this;
                    reqwest({
                        url: '/api/users/now/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.user_info = resp;
                            self.login_or = true
                            if(self.user_info.id == {{ user_id }}){
                                document.querySelector('#editButton').style.cssText = "float: right;display: ";
                            }
                        },
                        error:function (err) {
                            json_msg = JSON.parse(err.response);
                            self.login_or = false
                        }
                    })
                },
                displayBody:function () {
                    document.querySelector('#home-page').style.cssText = "display:";
                }
            },
             ready:function () {
                 this.request_user();
                 this.getUser();
                 this.displayBody();
            }
        })
    </script>
</body>
</html>

templates/question.html
{% load static%}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>问题</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}" media="screen" title="no title" charset="utf-8">
    {% include 'css_js.html' %}
</head>
<body id="app">
    <div id="home-page" style="display: none">
    {% include 'top_nav.html' %}
    <div class="ui basic segment container" style="top: 35px">
        <div class="on the line" style="margin: 50px 290px 16px 0px;">
            <span class="active item all question">
              全部问题
            </span>
        </div>
        <div class="ui divider"></div>
        <button v-for="topic in topics" class="ui basic circular button" style="height:24px;padding:5px;border: 1px">
            <span v-on:click="sendTopic(topic)" style="color: #259;font-weight: normal">[[ topic.name ]]</span>
        </button>
        <div class="ui divider"></div>
        <div v-for="question in questions" class="ui items" style="margin: 0">
            <div class="item">
                <div class="content" style="padding-left:10px;">
                    <div>
                        <img class="right floated mini ui image" style="height: 30px;width: 30px" :src="question.author.avatar">
                        <div class="meta">
                            <a href="/profile/[[question.author.id]]/" style="font-weight:bold;color:#000000;">[[ question.author.name ]],</a>
                            <span style="color:#BFBFBF;font-size: 13px">[[ question.author.desc ]]</span>
                        </div>
                    </div>
                    <a href="/question/[[question.id]]/" class="header" style="color:#2e5e9f;font-size:14px;margin-top: 8px">
                        [[ question.title ]]
                    </a>
                    <p style="font-size: 13px;margin-top: 5px">
                        [[ question.desc ]]
                    </p>
                </div>
            </div>
            <div class="ui divider"></div>
        </div>
        <div class="ui long button">
            <div class="header item">
                <a v-on:click="loadMoreQuestion">[[moreOrNot]]</a>
            </div>
        </div>
    </div>
    {% include 'footer.html' %}
    </div>
    <script>
        Vue.config.delimiters = ["[[", "]]"];
        vm = new Vue({
            el: '#app',
            data:{
                moreOrNot:'加载更多',
                questions:[],
                user_info:'',
                login_or:false,
                topics:[],
                topicChoice: '首页',
                question:{
                    title:'',
                    desc: '',
                    topic:''
                }
            },
            methods:{
                addQuestionBtn:function () {
                    var self=this;
                    if (self.user_info==''){
                        return $('#register-modal').modal('show')
                    }else{
                        return $('#question-modal').modal('show');
                    }
                },
                ifLogin:function () {
                    var self=this;
                    if (self.user_info==''){
                        return $('#register-modal').modal('show')
                    }
                },
                addQuestion:function () {
                    var self = this;
                        reqwest({
                        url: '/api/questions/',
                        type: 'json',
                        method: 'post',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        data:{
                            title:self.question.title,
                            desc: self.question.desc,
                            topic:self.question.topic
                        },
                        success:function (resp) {
                            window.location.href= '/question/'+resp.id+'/'
                        }
                    })
                },
                getQuestion:function () {
                    var self = this;
                    reqwest({
                        url: '/api/only_questions/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.questions = resp;
                            if(resp.length<10){
                                self.moreOrNot = '没有了'
                            }
                        }
                    })
                },
                loadMoreQuestion:function () {
                    var self = this;
                    reqwest({
                        url: '/api/only_questions?p=' + self.questions.length,
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            before_len = self.questions.length;
                            console.log(before_len);
                            for(a in resp){
                                self.questions.push(resp[a])
                            }
                            after_len = self.questions.length;
                            console.log(after_len);
                            if (after_len-before_len<5){
                                self.moreOrNot = '没有了'
                            }
                        }
                    })
                },
                getTopic:function () {
                    var self = this;
                    reqwest({
                        url: '/api/topics/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.topics = resp
                        }
                    })
                },
                sendTopic:function (topic) {
                    var self = this;
                    reqwest({
                        url: '/api/only_questions?topic=' + topic.name,
                        type: 'json',
                        success:function (resp) {
                            self.questions = resp
                        }
                    })
                },
                request_user:function () {
                    var self = this;
                    reqwest({
                        url: '/api/users/now/',
                        type: 'json',
                        headers: Cookies.get('token')?{'Authorization': 'Token ' + Cookies.get('token')}:{},
                        success:function (resp) {
                            self.user_info = resp;
                            self.login_or = true
                            },
                        error:function (err) {
                            json_msg = JSON.parse(err.response);
                            self.login_or = false
                        }
                    })
                },
                logOut:function () {
                    Cookies.remove('token');
                    location.reload()
                },
                displayBody:function () {
                    document.querySelector('#home-page').style.cssText = "display:"
                }
            },
            ready:function () {
                this.request_user();
                this.getTopic();
                this.getQuestion();
                this.displayBody()
            }
        })
    </script>
</body>
</html>